[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "backend"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
